# Don't print a new line at the start of the prompt
add_newline = false

[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"
