#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    statusline_separator = "nil"
    # install nerd fonts
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    enable_tabline_filetype_icon = true
    enable_vimfiler_filetypeicon = false
    enable_vimfiler_gitstatus = true
    filemanager = "defx"
#
#
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "core#statusline"
  enable = false

[[layers]]
name = 'ctrlp'

[[layers]]
name = 'lang#javascript'
auto_fix= true
enable_flow_syntax = true

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#csharp"

[[layers]]
name = "lang#fsharp"

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#graphql'

[[custom_plugins]]
name = 'yuttie/comfortable-motion.vim'
merged = 0

#[[custom_plugins]]
#name = 'chriskempson/base16-vim'
#merged = 0

[[layers]]
name = "colorscheme"
merged = 0

[[custom_plugins]]
repo = "dracula/vim"
name = "dracula"
merged = false

[[custom_plugins]]
name = "peitalin/vim-jsx-typescript"

[[custom_plugins]]
name = "maxmellon/vim-jsx-pretty"
